tmdbOpen <- function (filename=NULL, driver=NULL) 
{
# Open a database generated by tm.site.
#
# filename - the path and name of the database file; if NULL a
#            dialog will be displayed to choose the file
#      
# driver - an optional database driver to manage the connection
  
  if (!require(RSQLite, quietly=TRUE)) {
    stop("Can't load the RSQLite package or one of its dependents")
  }

  if (is.null(filename)) {
  	tryCatch(
      filename <- file.choose(),
      error = function(e) {} # dialog cancelled
    )
    
    if (is.null(filename)) return( invisible(NULL) )
  }
  
  if (!file.exists(filename)) {
  	cat(paste("Can't find", substitute(filename)))
  	return(invisible(NULL))
  }
  
  if (is.null(driver)) {
  	driver <- dbDriver("SQLite")
  }
  
  con <- dbConnect(driver, filename)
  if (!tmdbValidate(con, show=FALSE)) {
  	dbDisconnect(con)
  	cat(paste(substitute(filename), "is not a valid tm.site database"))
  	return(invisible(NULL))
  }
  
  # Return the connection to the database
  con
}
