# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Attempts to position circles without overlap.
#' 
#' Given an input matrix of circle positions and sizes, attempts to position them
#' without overlap by iterating the pair-repulsion algorithm.
#' 
#' @param xyr 3 column matrix (centre x, centre y, radius)
#' @param xbound limit in X direction
#' @param ybound limit in Y direction
#' @param maxiter maximum number of iterations
#' 
#' @return the number of iterations performed.
#' 
iterate_layout <- function(xyr, xbound, ybound, maxiter) {
    .Call('woodland_iterate_layout', PACKAGE = 'woodland', xyr, xbound, ybound, maxiter)
}

